#!/bin/bash
# PORTMASTER: sims3, The Sims 3.sh
# The Sims 3 — generated by nxbootstrap pattern (NextOS-style)
# Supports: muOS, ArkOS, ROCKNIX, NextOS, PortMaster

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

NXBOOTSTRAP_FINISHED=0
NXBOOTSTRAP_ABORTING=0
nxbootstrap_finish() {
  [ "$NXBOOTSTRAP_FINISHED" = 0 ] || return 0
  NXBOOTSTRAP_FINISHED=1
  if command -v pm_finish >/dev/null 2>&1; then pm_finish || true; fi
}
nxbootstrap_abort_before_game() {
  local abort_status=$1
  [ "$NXBOOTSTRAP_ABORTING" = 0 ] || return 0
  NXBOOTSTRAP_ABORTING=1
  echo "== aborted before game start (status $abort_status) =="
  nxbootstrap_finish
  exit "$abort_status"
}
nxbootstrap_install_early_traps() {
  trap 'nxbootstrap_abort_before_game 130' INT
  trap 'nxbootstrap_abort_before_game 143' TERM
  trap 'nxbootstrap_abort_before_game 129' HUP
}
trap nxbootstrap_finish EXIT
nxbootstrap_install_early_traps

# Analog sticks hint (PortMaster integration)
NXBOOTSTRAP_ANALOG_STICKS_HINT=""
unset NXINPUT_ANALOG_STICKS_HINT

# Find real PortMaster control.txt (NextOS pattern)
controlfolder=""
NXBOOTSTRAP_PM_ROOTS=(
  "/opt/system/Tools/PortMaster" "/opt/tools/PortMaster"
  "$XDG_DATA_HOME/PortMaster" "/storage/.config/PortMaster"
  "/var/data/PortMaster" "/PortMaster"
  "/roms/tools/PortMaster" "/roms2/tools/PortMaster"
  "/storage/roms/ports/PortMaster" "/storage/roms/Ports/PortMaster"
  "/roms/ports/PortMaster" "/roms/Ports/PortMaster"
  "/roms2/ports/PortMaster" "/roms2/Ports/PortMaster"
  "/userdata/roms/ports/PortMaster"
  "/userdata/system/.local/share/PortMaster"
  "/mnt/ports/PortMaster" "/mnt/Ports/PortMaster"
  "/mnt/mmc/MUOS/PortMaster" "/mnt/mmc/ports/PortMaster"
  "/mnt/SDCARD/Apps/PortMaster/PortMaster"
  "/mnt/sdcard/Roms/.portmaster/PortMaster"
)
for NXBOOTSTRAP_PM_CANDIDATE in "${NXBOOTSTRAP_PM_ROOTS[@]}"; do
  [ -f "$NXBOOTSTRAP_PM_CANDIDATE/control.txt" ] && \
    [ ! -L "$NXBOOTSTRAP_PM_CANDIDATE/control.txt" ] || continue
  NXBOOTSTRAP_PM_REAL=$(readlink -f "$NXBOOTSTRAP_PM_CANDIDATE" 2>/dev/null) || continue
  [ -d "$NXBOOTSTRAP_PM_REAL" ] && \
    [ -f "$NXBOOTSTRAP_PM_REAL/control.txt" ] && \
    [ ! -L "$NXBOOTSTRAP_PM_REAL/control.txt" ] || continue
  controlfolder=$NXBOOTSTRAP_PM_REAL
  break
done
unset NXBOOTSTRAP_PM_ROOTS NXBOOTSTRAP_PM_CANDIDATE NXBOOTSTRAP_PM_REAL
[ -n "$controlfolder" ] || controlfolder="/storage/.config/PortMaster"

# Source firmware config (NextOS pattern)
NXCOMPAT_PORTMASTER_DIR=""
CFW_NAME=""
DEVICE_NAME=""
DISPLAY_WIDTH=""
DISPLAY_HEIGHT=""
sdl_controllerconfig=""
ESUDO=""
CUR_TTY=""
ANALOGSTICKS=""
ANALOG_STICKS=""

if [ -f "$controlfolder/control.txt" ] && [ ! -L "$controlfolder/control.txt" ]; then
  source "$controlfolder/control.txt"
  trap nxbootstrap_finish EXIT
  nxbootstrap_install_early_traps
  case "${CFW_NAME-}" in
    *[!A-Za-z0-9._-]*|'') NXBOOTSTRAP_MOD_NAME='' ;;
    *) NXBOOTSTRAP_MOD_NAME=$CFW_NAME ;;
  esac
  if [ -n "$NXBOOTSTRAP_MOD_NAME" ] && \
     [ -f "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt" ] && \
     [ ! -L "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt" ]; then
    source "${controlfolder}/mod_${NXBOOTSTRAP_MOD_NAME}.txt"
    trap nxbootstrap_finish EXIT
    nxbootstrap_install_early_traps
  fi
  command -v get_controls >/dev/null 2>&1 && get_controls
  case "${ANALOGSTICKS:-${ANALOG_STICKS:-}}" in
    0|1|2)
      NXBOOTSTRAP_ANALOG_STICKS_HINT=${ANALOGSTICKS:-${ANALOG_STICKS:-}}
      export NXINPUT_ANALOG_STICKS_HINT="$NXBOOTSTRAP_ANALOG_STICKS_HINT"
      ;;
    *)
      NXBOOTSTRAP_ANALOG_STICKS_HINT=""
      unset NXINPUT_ANALOG_STICKS_HINT
      ;;
  esac
  trap nxbootstrap_finish EXIT
  nxbootstrap_install_early_traps
  export NXCOMPAT_PORTMASTER_DIR="$controlfolder"
else
  unset NXCOMPAT_PORTMASTER_DIR
fi

# Game directory (NextOS pattern)
GAMEDIR="/$directory/ports/sims3"
[ -d "$GAMEDIR" ] || GAMEDIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)/sims3"
cd "$GAMEDIR" || exit 1
GAMEDIR=$(pwd -P)

# Log rotation
[ -s "$GAMEDIR/log.txt" ] && mv -f "$GAMEDIR/log.txt" "$GAMEDIR/log.prev.txt" 2>/dev/null
exec > "$GAMEDIR/log.txt" 2>&1
echo "== The Sims 3 | nxbootstrap pattern | cfw=${CFW_NAME:-none} =="

# Executable validation (NextOS pattern)
NXBOOTSTRAP_EXECUTABLE=$(readlink -f "$GAMEDIR/sims3_s3e_loader" 2>/dev/null) || NXBOOTSTRAP_EXECUTABLE=""
case "$NXBOOTSTRAP_EXECUTABLE" in
  "$GAMEDIR"/*) ;;
  *) NXBOOTSTRAP_EXECUTABLE="" ;;
esac
if [ -z "$NXBOOTSTRAP_EXECUTABLE" ] || [ ! -f "$NXBOOTSTRAP_EXECUTABLE" ] || \
   [ ! -s "$NXBOOTSTRAP_EXECUTABLE" ] || [ -L "$GAMEDIR/sims3_s3e_loader" ]; then
  echo "ERROR: executable is missing or unsafe: sims3_s3e_loader"
  nxbootstrap_finish
  exit 1
fi

# Exec bits (NextOS pattern)
$ESUDO chmod +x "$NXBOOTSTRAP_EXECUTABLE" "$GAMEDIR"/*.sh \
  "$GAMEDIR/gatito-extract"/*.sh 2>/dev/null || true
$ESUDO chmod 666 "$CUR_TTY" /dev/uinput 2>/dev/null || true

# Console dark during KMSDRM transition
[ -n "$CUR_TTY" ] && [ -c "$CUR_TTY" ] && \
  printf '\033[?25l\033[2J\033[H' > "$CUR_TTY" 2>/dev/null || true

# Instance lock (NextOS pattern)
NXBOOTSTRAP_LOCK_ROOT=${XDG_RUNTIME_DIR:-}
if [ "${NXBOOTSTRAP_LOCK_ROOT#/}" = "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -d "$NXBOOTSTRAP_LOCK_ROOT" ] || [ -L "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_ROOT" ] || [ ! -w "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -x "$NXBOOTSTRAP_LOCK_ROOT" ]; then
  NXBOOTSTRAP_LOCK_ROOT=/tmp
fi
if [ ! -d "$NXBOOTSTRAP_LOCK_ROOT" ] || [ -L "$NXBOOTSTRAP_LOCK_ROOT" ] || \
   [ ! -w "$NXBOOTSTRAP_LOCK_ROOT" ] || [ ! -x "$NXBOOTSTRAP_LOCK_ROOT" ]; then
  echo "ERROR: no safe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
fi
NXBOOTSTRAP_LOCK_ROOT=$(cd "$NXBOOTSTRAP_LOCK_ROOT" 2>/dev/null && pwd -P) || {
  echo "ERROR: no safe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
}
case "$NXBOOTSTRAP_LOCK_ROOT" in
  "$GAMEDIR"|"$GAMEDIR"/*) 
    echo "ERROR: instance lock directory must be outside the game"
    nxbootstrap_finish
    exit 1
    ;;
esac
NXBOOTSTRAP_LOCK_DIR="$NXBOOTSTRAP_LOCK_ROOT/.nxbootstrap-${UID:-$(id -u)}"
if [ ! -e "$NXBOOTSTRAP_LOCK_DIR" ] && [ ! -L "$NXBOOTSTRAP_LOCK_DIR" ]; then
  (umask 077; mkdir "$NXBOOTSTRAP_LOCK_DIR") 2>/dev/null || true
fi
if [ ! -d "$NXBOOTSTRAP_LOCK_DIR" ] || [ -L "$NXBOOTSTRAP_LOCK_DIR" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_DIR" ] || [ ! -w "$NXBOOTSTRAP_LOCK_DIR" ] || \
   [ ! -x "$NXBOOTSTRAP_LOCK_DIR" ] || \
   ! chmod 0700 "$NXBOOTSTRAP_LOCK_DIR" 2>/dev/null; then
  echo "ERROR: unsafe runtime directory for the instance lock"
  nxbootstrap_finish
  exit 1
fi
NXBOOTSTRAP_LOCK_FILE="$NXBOOTSTRAP_LOCK_DIR/nxport-sims3.flock"
if [ -e "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ]; then
  if [ ! -f "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ] || \
     [ ! -O "$NXBOOTSTRAP_LOCK_FILE" ]; then
    echo "ERROR: unsafe instance lock file"
    nxbootstrap_finish
    exit 1
  fi
fi
NXBOOTSTRAP_OLD_UMASK=$(umask)
umask 077
{ exec 9>&-; } 2>/dev/null || true
if ! { exec 9>>"$NXBOOTSTRAP_LOCK_FILE"; } 2>/dev/null; then
  umask "$NXBOOTSTRAP_OLD_UMASK"
  echo "ERROR: cannot open the instance lock"
  nxbootstrap_finish
  exit 1
fi
umask "$NXBOOTSTRAP_OLD_UMASK"
NXBOOTSTRAP_LOCK_META=()
IFS=' ' read -r -a NXBOOTSTRAP_LOCK_META \
  <<< "$(LC_ALL=C command ls -Lldn /proc/self/fd/9 2>/dev/null)"
NXBOOTSTRAP_LOCK_LINKS=${NXBOOTSTRAP_LOCK_META[1]:-}
if [ ! -f "$NXBOOTSTRAP_LOCK_FILE" ] || [ -L "$NXBOOTSTRAP_LOCK_FILE" ] || \
   [ ! -O "$NXBOOTSTRAP_LOCK_FILE" ] || [ "$NXBOOTSTRAP_LOCK_LINKS" != 1 ] || \
   ! [ "$NXBOOTSTRAP_LOCK_FILE" -ef /proc/self/fd/9 ]; then
  { exec 9>&-; } 2>/dev/null || true
  echo "ERROR: instance lock identity is unsafe"
  nxbootstrap_finish
  exit 1
fi
unset NXBOOTSTRAP_LOCK_META NXBOOTSTRAP_LOCK_LINKS
if ! flock -n 9; then
  echo "another instance holds the lock; not double-launching"
  nxbootstrap_finish
  exit 1
fi

# NXExtract owner-data phase (BYO-data pattern) - Gatito Extractor
NXDIR=""
[ -f "$GAMEDIR/gatito-extract/run-extractor.sh" ] && NXDIR="$GAMEDIR/gatito-extract"
[ -z "$NXDIR" ] && [ -f "$GAMEDIR/run-extractor.sh" ] && NXDIR="$GAMEDIR"
# NxExtract owner-data phase (NextOS pattern) - Gatito Extractor
NXEXTRACT_REQUESTED=1
if [ "$NXEXTRACT_REQUESTED" = 1 ]; then
  NXEXTRACT_INCOMPLETE=0
  [ -n "$NXDIR" ] && [ ! -L "$NXDIR" ] || NXEXTRACT_INCOMPLETE=1
  for nxfile in "$GAMEDIR/extractor.json" "$NXDIR/run-extractor.sh" \
    "$NXDIR/nxextract-runtime-env.sh" "$NXDIR/nxextract-ui"; do
    [ -f "$nxfile" ] && [ -s "$nxfile" ] && [ ! -L "$nxfile" ] || NXEXTRACT_INCOMPLETE=1
  done
  if [ "$NXEXTRACT_INCOMPLETE" = 1 ]; then
    echo "ERROR: incomplete NxExtract integration"
    nxbootstrap_finish
    exit 1
  fi
  $ESUDO chmod +x "$NXDIR"/*.sh 2>/dev/null || true
  $ESUDO chmod +x "$NXDIR/nxextract-ui-ptbr" 2>/dev/null || true
  NXEXTRACT_GAME_DIR="$GAMEDIR" \
    bash "$NXDIR/run-extractor.sh" || {
      echo "ERROR: game data installation did not complete"
      nxbootstrap_finish
      exit 1
    }
fi
unset NXDIR NXEXTRACT_REQUESTED NXEXTRACT_INCOMPLETE nxfile

# Manifest-owned payload gate: extraction/prepare must finish before launch
NXBOOTSTRAP_REQUIRED_FILES='sims3_s3e_loader
game/game.s3e.unpacked
game/assets'
while IFS= read -r required_file; do
  [ -n "$required_file" ] || continue
  required_path=$(readlink -f "$GAMEDIR/$required_file" 2>/dev/null) || required_path=""
  case "$required_path" in
    "$GAMEDIR"/*) ;;
    *) required_path="" ;;
  esac
  if [ -z "$required_path" ] || [ ! -f "$required_path" ] || \
     [ ! -s "$required_path" ] || [ -L "$GAMEDIR/$required_file" ]; then
    echo "ERROR: required file is missing or unsafe: $required_file"
    nxbootstrap_finish
    exit 1
  fi
done <<< "$NXBOOTSTRAP_REQUIRED_FILES"
unset NXBOOTSTRAP_REQUIRED_FILES required_file required_path

# Saves and configuration stay inside the port directory (NextOS pattern)
export HOME="$GAMEDIR"

# SDL controller mapping (PortMaster)
[ -n "$sdl_controllerconfig" ] && export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"

# Optional per-port adapter (port-env.sh pattern)
BIN="$GAMEDIR/sims3_s3e_loader"
readonly NXBOOTSTRAP_ANALOG_STICKS_HINT
[ -f "$GAMEDIR/port-env.sh" ] && [ ! -L "$GAMEDIR/port-env.sh" ] && . "$GAMEDIR/port-env.sh"

command -v pm_platform_helper >/dev/null 2>&1 && pm_platform_helper "$BIN"

# Host phase ends: library paths now (NextOS pattern)
LIBS=""
for d in "$controlfolder/libs" "$controlfolder/libs.armhf" "$controlfolder/libs.aarch64" \
         "$GAMEDIR/libs.armhf" "$GAMEDIR/libs.aarch64" \
         /usr/local/lib/aarch64-linux-gnu /usr/local/lib64 /usr/local/lib \
         /usr/lib/aarch64-linux-gnu /lib/aarch64-linux-gnu \
         /usr/lib/arm-linux-gnueabihf /lib/arm-linux-gnueabihf \
         /usr/lib64 /lib64 /usr/lib /lib; do
  [ -n "$d" ] && [ -d "$d" ] && LIBS="${LIBS:+$LIBS:}$d"
done
export LD_LIBRARY_PATH="${LIBS}:$GAMEDIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
trap nxbootstrap_finish EXIT
nxbootstrap_install_early_traps

# Capabilities declaration (NextOS pattern)
case "$NXBOOTSTRAP_ANALOG_STICKS_HINT" in
  0|1|2) export NXINPUT_ANALOG_STICKS_HINT="$NXBOOTSTRAP_ANALOG_STICKS_HINT" ;;
  *) unset NXINPUT_ANALOG_STICKS_HINT ;;
esac
export NXCOMPAT_PORT_ID=sims3
export NXCOMPAT_GAME_DIR="$GAMEDIR"
export NXCOMPAT_REQUIRED_CAPABILITIES='
host.portmaster
host.aarch64-libs
graphics.window
graphics.gles2
graphics.egl
graphics.egl-config
graphics.drawable
audio.output-open
input.controller-mapping
input.controller-api'
export NXCOMPAT_ENABLED_QUIRKS='video.fbcon-fallback'
export NXCOMPAT_RUNTIME_REPORT=log-and-logo

# S3E Extension stubs via LD_PRELOAD (NextOS LD_PRELOAD pattern)
# Use armhf stubs (ARMv7) as primary since our loader is ARMv7
STUBS_DIR="$GAMEDIR/libs.armhf"
# Fallback to aarch64 stubs if available and we're on AArch64
[ "$(uname -m)" = "aarch64" ] && [ -d "$GAMEDIR/libs.aarch64" ] && STUBS_DIR="$GAMEDIR/libs.aarch64"
STUBS_PRELOAD=""
for stub in libs3eAndroidJNI.so libs3eVFS.so; do
  [ -f "$STUBS_DIR/$stub" ] && STUBS_PRELOAD="${STUBS_PRELOAD:+$STUBS_PRELOAD:}$STUBS_DIR/$stub"
done
[ -n "$STUBS_PRELOAD" ] && export LD_PRELOAD="${STUBS_PRELOAD}${LD_PRELOAD:+:$LD_PRELOAD}"
echo "[INFO] S3E Extension Stubs: ${STUBS_PRELOAD:-none found}"

# Smart video fallback (NextOS pattern)
if [ -f "$GAMEDIR/log.txt" ] && grep -q "ERROR: Could not queue pageflip" "$GAMEDIR/log.txt" 2>/dev/null; then
  echo "[WARN] Pageflip error detected, forcing fbcon"
  export SDL_VIDEODRIVER=fbcon
  export SDL_AUDIODRIVER=alsa
  export SDL_RENDER_DRIVER=software
elif [ -n "${WAYLAND_DISPLAY:-}" ] && [ ! -e /dev/dri/renderD128 ]; then
  echo "[WARN] Wayland without GPU, forcing fbcon"
  export SDL_VIDEODRIVER=fbcon
  export SDL_AUDIODRIVER=alsa
elif [ -e /dev/fb0 ] && [ ! -e /dev/dri/card0 ]; then
  echo "[INFO] Framebuffer only, using fbcon"
  export SDL_VIDEODRIVER=fbcon
  export SDL_AUDIODRIVER=alsa
fi

# Display resolution
export SIMS3_W="${SIMS3_W:-${DISPLAY_WIDTH:-640}}"
export SIMS3_H="${SIMS3_H:-${DISPLAY_HEIGHT:-480}}"

echo "=== The Sims 3 Launch ==="
echo "CFW=$CFW_NAME"
echo "DEVICE=${DEVICE_NAME:-$(uname -n)}"
echo "ARCH=$(uname -m)"
echo "Resolution: ${SIMS3_W}x${SIMS3_H}"
echo "Loader: $BIN"
echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
echo "SDL_VIDEODRIVER=${SDL_VIDEODRIVER:-auto}"
echo "SDL_AUDIODRIVER=${SDL_AUDIODRIVER:-auto}"
[ -n "$STUBS_PRELOAD" ] && echo "LD_PRELOAD=$STUBS_PRELOAD"

# Signal handling (NextOS pattern)
game_pid=
NXBOOTSTRAP_CHILD_STARTTIME=
NXBOOTSTRAP_SHUTDOWN_REQUESTED=0
NXBOOTSTRAP_TERM_SENT=0
NXBOOTSTRAP_SIGNAL_COUNT=0
nxbootstrap_capture_child_starttime() {
  local child_stat child_rest
  case "$game_pid" in ''|*[!0-9]*) return 1 ;; esac
  IFS= read -r child_stat < "/proc/$game_pid/stat" 2>/dev/null || return 1
  child_rest=${child_stat##*) }
  set -- $child_rest
  [ "$#" -ge 20 ] || return 1
  NXBOOTSTRAP_CHILD_STARTTIME=${20}
}
nxbootstrap_child_alive() {
  local child_stat child_rest child_state child_start
  case "$game_pid" in ''|*[!0-9]*) return 1 ;; esac
  [ -n "$NXBOOTSTRAP_CHILD_STARTTIME" ] || return 1
  builtin kill -0 "$game_pid" 2>/dev/null || return 1
  IFS= read -r child_stat < "/proc/$game_pid/stat" 2>/dev/null || return 1
  child_rest=${child_stat##*) }
  set -- $child_rest
  [ "$#" -ge 20 ] || return 1
  child_state=$1
  child_start=${20}
  case "$child_state" in Z|X) return 1 ;; esac
  [ "$child_start" = "$NXBOOTSTRAP_CHILD_STARTTIME" ]
}
nxbootstrap_signal_child() {
  [ "$NXBOOTSTRAP_TERM_SENT" = 0 ] || return 0
  [ -n "$NXBOOTSTRAP_CHILD_STARTTIME" ] || nxbootstrap_capture_child_starttime || return 0
  nxbootstrap_child_alive || return 0
  NXBOOTSTRAP_TERM_SENT=1
  builtin kill -TERM "$game_pid" 2>/dev/null || true
}
nxbootstrap_request_shutdown() {
  NXBOOTSTRAP_SIGNAL_COUNT=$((NXBOOTSTRAP_SIGNAL_COUNT + 1))
  if [ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 0 ]; then
    NXBOOTSTRAP_SHUTDOWN_REQUESTED=1
  fi
  nxbootstrap_signal_child || true
}
trap nxbootstrap_request_shutdown INT TERM HUP

# Launch game (NextOS pattern - close lock fd in child only)
GAME_IMAGE="$GAMEDIR/game/game.s3e.unpacked"
GAME_ROOT="$GAMEDIR/game"

if [ -n "$BIN_PRELOAD" ]; then
  LD_PRELOAD="$BIN_PRELOAD${LD_PRELOAD:+:$LD_PRELOAD}" "$BIN" --run --root "$GAME_ROOT" "$GAME_IMAGE" "$@" 9>&- &
else
  "$BIN" --run --root "$GAME_ROOT" "$GAME_IMAGE" "$@" 9>&- &
fi
game_pid=$!
nxbootstrap_capture_child_starttime || NXBOOTSTRAP_CHILD_STARTTIME=""
[ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 0 ] || nxbootstrap_signal_child
if wait "$game_pid"; then status=0; else status=$?; fi
if [ "$NXBOOTSTRAP_SHUTDOWN_REQUESTED" = 1 ]; then
  trap '' INT TERM HUP
  NXBOOTSTRAP_SHUTDOWN_TICKS=10
  while [ "$NXBOOTSTRAP_SHUTDOWN_TICKS" -gt 0 ] && nxbootstrap_child_alive; do
    sleep 1 || true
    NXBOOTSTRAP_SHUTDOWN_TICKS=$((NXBOOTSTRAP_SHUTDOWN_TICKS - 1))
  done
  if nxbootstrap_child_alive; then
    echo "== termination deadline expired; sending KILL =="
    builtin kill -KILL "$game_pid" 2>/dev/null || true
  fi
  NXBOOTSTRAP_REWAIT_BUDGET=$NXBOOTSTRAP_SIGNAL_COUNT
  while [ "$NXBOOTSTRAP_REWAIT_BUDGET" -gt 0 ]; do
    case "$status" in 129|130|143) ;; *) break ;; esac
    NXBOOTSTRAP_REWAIT_BUDGET=$((NXBOOTSTRAP_REWAIT_BUDGET - 1))
    if wait "$game_pid" 2>/dev/null; then status=0; else status=$?; fi
  done
else
  while [ "$status" -gt 128 ] && nxbootstrap_child_alive; do
    if wait "$game_pid"; then status=0; else status=$?; fi
  done
fi
echo "== end (status $status) =="

# Reset console
[ -n "$CUR_TTY" ] && [ -c "$CUR_TTY" ] && printf '\033c' > "$CUR_TTY" 2>/dev/null
nxbootstrap_finish
exit $status